| Faculdade | Curso | Disciplina | Professor | Período |
| :- | :- | :- | :-| :-: |
|Universidade Estácio de Sá | Análise e Desenvolvimento de Sistemas | Tópicos de Big Data e Python | Prof. Fabio da Roza Oliveira | 2024.2 |

---

# Análise de Dados

Importando Bibliotecas e dados da Tabela:

In [17]:
import pandas as pd

data = pd.read_excel("INMET_SE_SP_A763_MARILIA_01-01-2024_A_30-09-2024.xlsx")
data.describe()

,Data,"PRECIPITAÇAO TOTAL, HORARIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇAO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
count,6576,6545.000000,6545.000000,6545.000000,6545.000000,3439.000000,6545.000000,6545.000000,6545.000000,6545.000000,6545.000000,6541.000000,6545.000000,6544.000000,6545.000000,4039.000000,4038.000000,4039.000000
mean,2024-05-16 12:00:00,0.123911,940.252147,940.523957,939.994607,1430.192033,23.978732,13.677937,24.638747,23.356226,14.232987,13.181822,60.285256,54.785605,57.536440,145.763803,5.100892,1.742857
min,2024-01-01 00:00:00,0.000000,929.300000,930.100000,929.200000,0.000000,6.200000,-9.900000,6.400000,6.000000,-6.900000,-9.300000,9.000000,7.000000,8.000000,1.000000,0.500000,0.100000
25%,2024-03-09 00:00:00,0.000000,938.100000,938.400000,937.800000,359.750000,21.000000,9.600000,21.500000,20.500000,10.000000,9.200000,42.000000,37.000000,40.000000,69.000000,3.500000,1.100000
50%,2024-05-16 12:00:00,0.000000,940.000000,940.300000,939.800000,1398.400000,24.100000,14.500000,24.700000,23.500000,15.000000,14.100000,60.000000,53.000000,56.000000,125.000000,5.000000,1.700000
75%,2024-07-24 00:00:00,0.000000,942.300000,942.500000,942.000000,2360.500000,27.400000,18.700000,28.200000,26.600000,19.200000,18.100000,80.000000,73.000000,77.000000,193.000000,6.500000,2.300000
max,2024-09-30 00:00:00,67.000000,949.400000,949.400000,949.200000,4266.600000,38.100000,23.600000,38.900000,37.700000,24.700000,22.800000,100.000000,100.000000,100.000000,360.000000,17.900000,5.500000
std,NaN,1.450577,3.075464,3.055219,3.083314,1079.744113,4.980744,5.763238,5.107810,4.841071,5.727762,5.772334,22.564694,22.294543,22.507244,100.778705,2.153047,0.833800

In [18]:
# Exibindo as Colunas da tabela
data.columns

Index(['Data', 'Hora UTC', 'PRECIPITAÇAO TOTAL, HORARIO (mm)',
       'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)',
       'PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)',
       'PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)',
       'RADIACAO GLOBAL (Kj/m²)',
       'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)',
       'TEMPERATURA DO PONTO DE ORVALHO (°C)',
       'TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)',
       'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)',
       'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)',
       'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)',
       'UMIDADE RELATIVA DO AR, HORARIA (%)',
       'VENTO, DIREÇAO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)',
       'VENTO, VELOCIDADE HORARIA (m/s)'],
      dtype='object')

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6576 entries, 0 to 6575
Data columns (total 19 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Data                                                   6576 non-null   datetime64[ns]
 1   Hora UTC                                               6576 non-null   object
 2   PRECIPITAÇAO TOTAL, HORARIO (mm)                       6545 non-null   float64
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  6545 non-null   float64
 4   PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        6545 non-null   float64
 5   PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       6545 non-null   float64
 6   RADIACAO GLOBAL (Kj/m²)                                3439 non-null   float64
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           6545 non-null   float64
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   6545 non-null   float64
 9   TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)             6545 non-null   float64
 10  TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)             6545 non-null   float64
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       6545 non-null   float64
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       6541 non-null   float64
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               6545 non-null   float64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               6544 non-null   float64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    6545 non-null   float64
 16  VENTO, DIREÇAO HORARIA (gr) (° (gr))                   4039 non-null   float64
 17  VENTO, RAJADA MAXIMA (m/s)                             4038 non-null   float64
 18  VENTO, VELOCIDADE HORARIA (m/s)                        4039 non-null   float64
dtypes: datetime64[ns](1), float64(17), object(1)
memory usage: 976.3+ KB

In [20]:
# Exibindo Quantidade de Linhas e Colunas
data.shape

(6576, 19)

In [21]:
# Leitura da Tabela
data.head(10)

,Data,Hora UTC,"PRECIPITAÇAO TOTAL, HORARIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇAO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2024-01-01,0000 UTC,0.0,937.6,937.7,936.7,NaN,25.9,14.1,26.3,25.9,14.3,13.8,49.0,46.0,48.0,153.0,6.2,2.3
1,2024-01-01,0100 UTC,0.0,938.2,938.2,937.6,NaN,24.9,14.6,25.9,24.8,14.7,14.0,53.0,48.0,53.0,151.0,7.0,1.5
2,2024-01-01,0200 UTC,0.0,938.5,938.5,938.2,NaN,23.5,15.3,25.0,23.5,15.4,14.5,60.0,52.0,60.0,144.0,6.1,1.5
3,2024-01-01,0300 UTC,0.0,938.9,939.0,938.5,NaN,23.0,15.6,23.6,23.0,15.6,15.2,63.0,60.0,63.0,107.0,7.0,1.9
4,2024-01-01,0400 UTC,0.0,938.7,939.0,938.6,0.1,22.2,15.8,23.0,22.2,15.9,15.5,68.0,63.0,67.0,110.0,5.7,2.0
5,2024-01-01,0500 UTC,0.0,938.3,938.7,938.2,NaN,21.2,15.7,22.2,21.2,15.9,15.6,71.0,67.0,71.0,131.0,6.3,2.4
6,2024-01-01,0600 UTC,0.0,937.3,938.3,937.3,NaN,20.7,15.9,21.2,20.7,15.9,15.7,74.0,71.0,74.0,118.0,5.1,2.7
7,2024-01-01,0700 UTC,0.0,936.8,937.3,936.8,NaN,20.2,16.2,20.7,20.2,16.3,15.9,78.0,74.0,78.0,146.0,6.8,2.5
8,2024-01-01,0800 UTC,0.0,937.2,937.2,936.8,NaN,19.3,16.2,20.2,19.3,16.3,16.2,82.0,78.0,82.0,152.0,6.0,1.7
9,2024-01-01,0900 UTC,0.0,937.7,937.8,937.2,5.5,18.8,16.0,19.3,18.8,16.3,16.0,85.0,82.0,84.0,145.0,7.1,2.2

In [22]:
data.count()

Data                                                     6576
Hora UTC                                                 6576
PRECIPITAÇAO TOTAL, HORARIO (mm)                         6545
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)    6545
PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)          6545
PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)         6545
RADIACAO GLOBAL (Kj/m²)                                  3439
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)             6545
TEMPERATURA DO PONTO DE ORVALHO (°C)                     6545
TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)               6545
TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)               6545
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)         6545
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)         6541
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                 6545
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 6544
UMIDADE RELATIVA DO AR, HORARIA (%)                      6545
VENTO, DIREÇAO HORARIA (gr) (° (gr))                     4039
VENTO, RAJADA MAXIMA (m/s)                               4038
VENTO, VELOCIDADE HORARIA (m/s)                          4039
dtype: int64

In [23]:
data_cleaned = data.drop (['Data', 'Hora UTC', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (Kj/m²)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)','VENTO, DIREÇAO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)'], axis=1)
data_cleaned.head()

,"PRECIPITAÇAO TOTAL, HORARIO (mm)","TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)"
0,0.0,25.9,26.3,25.9,49.0,46.0,48.0
1,0.0,24.9,25.9,24.8,53.0,48.0,53.0
2,0.0,23.5,25.0,23.5,60.0,52.0,60.0
3,0.0,23.0,23.6,23.0,63.0,60.0,63.0
4,0.0,22.2,23.0,22.2,68.0,63.0,67.0

In [24]:
data_cleaned.describe()

,"PRECIPITAÇAO TOTAL, HORARIO (mm)","TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)"
count,6545.000000,6545.000000,6545.000000,6545.000000,6545.000000,6544.000000,6545.000000
mean,0.123911,23.978732,24.638747,23.356226,60.285256,54.785605,57.536440
std,1.450577,4.980744,5.107810,4.841071,22.564694,22.294543,22.507244
min,0.000000,6.200000,6.400000,6.000000,9.000000,7.000000,8.000000
25%,0.000000,21.000000,21.500000,20.500000,42.000000,37.000000,40.000000
50%,0.000000,24.100000,24.700000,23.500000,60.000000,53.000000,56.000000
75%,0.000000,27.400000,28.200000,26.600000,80.000000,73.000000,77.000000
max,67.000000,38.100000,38.900000,37.700000,100.000000,100.000000,100.000000

In [25]:
data_cleaned.isnull().sum()

PRECIPITAÇAO TOTAL, HORARIO (mm)                31
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)    31
TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)      31
TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)      31
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)        31
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)        32
UMIDADE RELATIVA DO AR, HORARIA (%)             31
dtype: int64

In [26]:
def num_missing(x):
  return sum(x.isnull())

In [27]:
import numpy as np

data_cleaned.apply(num_missing, axis=0) #axis=0 defines that function is to be applied on each column

PRECIPITAÇAO TOTAL, HORARIO (mm)                31
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)    31
TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)      31
TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)      31
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)        31
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)        32
UMIDADE RELATIVA DO AR, HORARIA (%)             31
dtype: int64

In [28]:
# Calculo da Mediana
median_prec = data['PRECIPITAÇAO TOTAL, HORARIO (mm)'].median()  
# Substitui valores nulos pela mediana
data_cleaned['PRECIPITAÇAO TOTAL, HORARIO (mm)'].fillna(median_prec, inplace=True)


median_tempb = data['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].median()  
# Substitui valores nulos pela mediana
data_cleaned['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].fillna(median_prec, inplace=True)


median_temmax = data['TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)'].median()  
# Substitui valores nulos pela mediana
data_cleaned['TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)'].fillna(median_prec, inplace=True)

median_tempmin = data['TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)'].median() 
# Substitui valores nulos pela mediana
data_cleaned['TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)'].fillna(median_prec, inplace=True)


median_ummax = data['UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)'].median()
# Substitui valores nulos pela mediana
data_cleaned['UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)'].fillna(median_prec, inplace=True)

median_ummin = data['UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)'].median()
# Substitui valores nulos pela mediana
data_cleaned['UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)'].fillna(median_prec, inplace=True)


median_umrel = data['UMIDADE RELATIVA DO AR, HORARIA (%)'].median()
# Substitui valores nulos pela mediana
data_cleaned['UMIDADE RELATIVA DO AR, HORARIA (%)'].fillna(median_prec, inplace=True)

data_cleaned.apply(num_missing, axis=0) #axis=0 defines that function is to be applied on each column

C:\Users\codem\AppData\Local\Temp\ipykernel_6452\1273573877.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['PRECIPITAÇAO TOTAL, HORARIO (mm)'].fillna(median_prec, inplace=True)
C:\Users\codem\AppData\Local\Temp\ipykernel_6452\1273573877.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].fillna(median_prec, inplace=True)
C:\Users\codem\AppData\Local\Temp\ipykernel_6452\1273573877.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)'].fillna(median_prec, inplace=True)
C:\Users\codem\AppData\Local\Temp\ipykernel_6452\1273573877.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)'].fillna(median_prec, inplace=True)
C:\Users\codem\AppData\Local\Temp\ipykernel_6452\1273573877.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)'].fillna(median_prec, inplace=True)
C:\Users\codem\AppData\Local\Temp\ipykernel_6452\1273573877.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)'].fillna(median_prec, inplace=True)
C:\Users\codem\AppData\Local\Temp\ipykernel_6452\1273573877.py:32: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['UMIDADE RELATIVA DO AR, HORARIA (%)'].fillna(median_prec, inplace=True)

PRECIPITAÇAO TOTAL, HORARIO (mm)                0
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)    0
TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)      0
TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)      0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)        0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)        0
UMIDADE RELATIVA DO AR, HORARIA (%)             0
dtype: int64

In [29]:
data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6576 entries, 0 to 6575
Data columns (total 7 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   PRECIPITAÇAO TOTAL, HORARIO (mm)              6576 non-null   float64
 1   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)  6576 non-null   float64
 2   TEMPERATURA MAXIMA NA HORA ANT. (AUT) (°C)    6576 non-null   float64
 3   TEMPERATURA MINIMA NA HORA ANT. (AUT) (°C)    6576 non-null   float64
 4   UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)      6576 non-null   float64
 5   UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)      6576 non-null   float64
 6   UMIDADE RELATIVA DO AR, HORARIA (%)           6576 non-null   float64
dtypes: float64(7)
memory usage: 359.8 KB